ml:
  image: ml-devel
  volumes:
  - /mnt/data/ml/:/mnt/data/ml/

ml-devel:
  extends:
    service: ml
  volumes:
  - ..:/src
  working_dir: /src/ruby

lab-ml-devel:
  extends:
    service: ml-devel
  volumes:
  - /mnt/data0/ml/:/mnt/data0/ml/

mysql:
  image: xi-nlp-mysql

virtuoso:
  image: xi-nlp-virtuoso

ml-nlp-devel:
  image: ml-nlp-devel
  links:
  - mysql
  - virtuoso
  volumes:
  - ..:/src
  - /mnt/data/ml/:/mnt/data/ml/
  working_dir: /src/ruby

lab-ml-nlp-devel:
  image: ml-nlp-devel
  links:
  - mysql
  - virtuoso
  volumes:
  - ..:/src
  - /mnt/data0/ml/:/mnt/data0/ml/
  working_dir: /src/ruby
