:res: /mnt/data/ml/docs/resources/fr/3categories/ssu/es1prod_06102017/
:classes:
  - :society
  - :sport
  - :_UNK_
:preprocess: :PDLW
:execution:
  - :transform
  - :classify
  - :evaluate
:transform:
  :name: :LSI
  :files:
    :dict: /usr/share/xi-ml/td/models/dictionary.json
    :tfidf: /usr/share/xi-ml/td/models/model_TFIDF.json
    :lsi: /usr/share/xi-ml/td/models/model_LSI.bin
:classify:
  :name: :MLPClassifier
  :file: /usr/share/xi-ml/td/models/model_MLP-multiclass_3c.json
