:execution:
  - :clean
:clean:
  - :name: Xi::ML::Preprocess::Cleaner::NLPCleaner
    :args:
      :lang: fr
      :filter: Xi::ML::Preprocess::Filter::PosNVFilter
  - :name: Xi::ML::Preprocess::Cleaner::PunctCleaner
    :args:
  - :name: Xi::ML::Preprocess::Cleaner::DigitCleaner
    :args:
  - :name: Xi::ML::Preprocess::Cleaner::LowercaseCleaner
    :args:
  - :name: Xi::ML::Preprocess::Cleaner::WhitespaceCleaner
    :args:
