:res: /mnt/data/ml/docs/resources/fr/3categories/ssu/
:version: es1prod_06102017
:classes:
  - :society
  - :sport
  - :_UNK_
:execution:
  - :clean
:clean:
  :preprocs:
    :LNV-PDLW:
      - :name: Xi::ML::Preprocess::Cleaner::NLPCleaner
        :args:
          :lang: fr
          :filter: Xi::ML::Preprocess::Filter::PosNVLemmasFilter
      - :name: Xi::ML::Preprocess::Cleaner::PunctCleaner
        :args:
      - :name: Xi::ML::Preprocess::Cleaner::DigitCleaner
        :args:
      - :name: Xi::ML::Preprocess::Cleaner::LowercaseCleaner
        :args:
      - :name: Xi::ML::Preprocess::Cleaner::WhitespaceCleaner
        :args:
