:res: /mnt/data/ml/docs/resources/fr/2categories/sn/
:classes:
  - :sport
  - :non-sport
:execution:
  - :extract
  - :build
  - :clean
:extract:
  :es:
    :name: es1preprod
    :ip: localhost
    :host: localhost
    :port: '9223'
  :esquery:
    :index:
      - article
      - product
    :type:
      - content
    :source:
      - :id
      - :lang
      - :site
      - :url
      - :title
      - :content
    :min_nchars: 200
  :hosts:
    :sport: ./conf/fr/hosts_2classes/sport_hosts.yml
    :non-sport: ./conf/fr/hosts_2classes/non-sport_hosts.yml
  :lang: :fr
  :query_filter: :url_regexp
:build:
  :division:
    :train: 80
    :dev: 10
    :test: 10
:clean:
  :preprocs:
    :PDLW:
      - :name: Xi::ML::Preprocess::Cleaner::PunctCleaner
        :args:
      - :name: Xi::ML::Preprocess::Cleaner::DigitCleaner
        :args:
      - :name: Xi::ML::Preprocess::Cleaner::LowercaseCleaner
        :args:
      - :name: Xi::ML::Preprocess::Cleaner::WhitespaceCleaner
        :args:
