:execution:
  - :clean
  - :transform
  - :classify
:clean:
  - :name: Xi::ML::Preprocess::Cleaner::PunctCleaner
    :args:
  - :name: Xi::ML::Preprocess::Cleaner::DigitCleaner
    :args:
  - :name: Xi::ML::Preprocess::Cleaner::LowercaseCleaner
    :args:
  - :name: Xi::ML::Preprocess::Cleaner::WhitespaceCleaner
    :args:
:transform:
  :name: :LSI
  :files:
    :dict: /usr/share/xi-ml/td/models/dictionary.json
    :tfidf: /usr/share/xi-ml/td/models/model_TFIDF.json
    :lsi: /usr/share/xi-ml/td/models/model_LSI.bin
:classify:
  :name: :MLPClassifier
  :file: /usr/share/xi-ml/td/models/model_MLP-multiclass_3c.json
