:res: /mnt/data/ml/resources/fr/es1preprod_22022017/
:classes:
  - society
  - sport
  - _UNK_
:preprocess: PDLW
:execution:
  - :classify
  - :evaluate
:transform:
  :name: LSI
  :files:
    :dict: /tmp/ml-resources/dictionary.txt
    :tfidf: /tmp/ml-resources/model_TFIDF.json
    :lsi: /tmp/ml-resources/model_LSI.bin
:classify:
  :name: LogisticRegression
  :file: /tmp/ml-resources/model_LR-multiclass-3c.json
