:res: /mnt/data/ml/resources/
:lang: fr
:classes:
  - society
  - sport
  - _UNK_
:execution:
  - :extract
  - :build
  - :clean
:extract:
  :es:
    :name: es1preprod
    :ip: '192.168.2.3'
    :host: localhost
    :port: '9223'
  :esquery:
    :index:
      - article
      - product
    :type:
      - content
    :source:
      - id
      - lang
      - site
      - url
      - title
      - content
    :min_nchars: 200
  :hosts:
    society: ./conf/fr/hosts_3classes/society_hosts.yml
    sport: ./conf/fr/hosts_3classes/sport_hosts.yml
    _UNK_: ./conf/fr/hosts_3classes/unk_hosts.yml
  :query_filter: url
:build:
  :division:
    :train: 80
    :dev: 10
    :test: 10
:clean:
  :preprocs:
    :PDLW:
      - :name: Xi::ML::Preprocess::Cleaner::PunctCleaner
        :args:
      - :name: Xi::ML::Preprocess::Cleaner::DigitCleaner
        :args:
      - :name: Xi::ML::Preprocess::Cleaner::LowercaseCleaner
        :args:
      - :name: Xi::ML::Preprocess::Cleaner::WhitespaceCleaner
        :args:
