:res: /mnt/data/ml/resources/
:version: es1preprod_22022017
:lang: fr
:classes:
  - society
  - sport
  - _UNK_
:execution:
  - :clean
:clean:
  :preprocs:
    :NV-PDLW:
      - :name: Xi::ML::Preprocess::Cleaner::DigitCleaner
        :args:
      - :name: Xi::ML::Preprocess::Cleaner::UpcaseCleaner
        :args:
      - :name: Xi::ML::Preprocess::Cleaner::NLPCleaner
        :args:
          :lang: fr
          :filter: Xi::ML::Preprocess::Filter::PosNVFilter
      - :name: Xi::ML::Preprocess::Cleaner::PunctCleaner
        :args:
      - :name: Xi::ML::Preprocess::Cleaner::LowercaseCleaner
        :args:
      - :name: Xi::ML::Preprocess::Cleaner::WhitespaceCleaner
        :args:
