ml:
  image: ml-python-devel
  volumes:
  - /mnt/data/ml/resources/:/mnt/data/ml/resources/

ml-devel:
  extends:
    service: ml
  volumes:
  - ..:/src
  working_dir: /src/python

lab-ml-devel:
  extends:
    service: ml-devel
  volumes:
  - /mnt/data0/ml/resources/:/mnt/data0/ml/resources/
