ml:
  image: ml-python-devel
  volumes:
  - /mnt/data/ml/docs/:/mnt/data/ml/docs/
  - /mnt/data/ml/colors/:/mnt/data/ml/colors/

ml-devel:
  extends:
    service: ml
  volumes:
  - ..:/src
  working_dir: /src/python

lab-ml-devel:
  extends:
    service: ml-devel
  volumes:
  - /mnt/data0/ml/docs/:/mnt/data0/ml/docs/
  - /mnt/data0/ml/colors/:/mnt/data0/ml/colors/
