ml:
  image: ml-python-devel
  volumes:
  - /mnt/data/ml/:/mnt/data/ml/

ml-devel:
  extends:
    service: ml
  volumes:
  - ..:/src
  working_dir: /src/python

lab-ml-devel:
  extends:
    service: ml-devel
  net: host
  volumes:
  - /mnt/data0/ml/:/mnt/data0/ml/
