res: /mnt/data/ml/docs/resources/fr/3categories/ssu/es1prod_06102017/
classes:
  - society
  - sport
  - _UNK_
preprocessings:
  - PDLW
dictionary:
  no_below: 5
  no_above: 0.75
  keep_n: 500000
transformations:
  LSI:
    num_topics: 300
    distributed: False
classifiers:
  MLPClassifier:
    classif_types:
      - multiclass
      - multilabel
    train_types:
      - offline
    chunk_sizes:
      - -1
      - 1000
      - 10000
      - 100000
      - 1000000
    kwargs:
      verbose: False
      solver: adam
      activation: relu
      max_iter: 200
      hidden_layer_sizes:
        - 100
execution:
  - train_trans
  - get_topics
  - transform_data
  - train_classifiers
  - test_classifiers
