res: /mnt/data/ml/docs/resources/fr/3categories/ssu/es1prod_06102017/
input:
  - data/society/preprocessed/PDLW/society_train.json
  - data/sport/preprocessed/PDLW/sport_train.json
  - data/_UNK_/preprocessed/PDLW/_UNK__train.json
dictionary: dictionary/dictionary_PDLW.txt
models:
  cbow:
    file: models/word2vec/cbow_PDLW/word2vec-cbow.bin
  skipgram:
    file: models/word2vec/skipgram_PDLW/word2vec-skipgram.bin
